#!/bin/sh
sudo apt -y install gcc curl make repo libxml2-utils flex m4
sudo apt -y install openjdk-8-jdk lib32stdc++6 libelf-dev mtools
sudo apt -y install libssl-dev pypy-enum34 python3-mako syslinux-utils
sudo apt -y install bc bison build-essential
sudo apt -y install ccache g++-multilib gcc-multilib
sudo apt -y install gnupg gperf imagemagick
sudo apt -y install lib32ncurses5-dev lib32readline-dev lib32z1-dev
sudo apt -y install libelf-dev liblz4-tool libncurses5
sudo apt -y install libncurses5-dev libsdl1.2-dev
sudo apt -y install libxml2 lzop pngcrush
sudo apt -y install rsync schedtool squashfs-tools
sudo apt -y install xsltproc zip zlib1g-dev
mkdir -p ~/bin
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
echo export PATH='$HOME/bin:$PATH' >> ~/.bashrc
echo ""
echo "If you want to build 'android-x86' iso, "
echo 'repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b r-x86'
echo ""
